### ISSUE TITLE
Mad Man #2

### ISSUE THREAD

**Issue by ProfessorManhattan** [rwaltr/dotfiles#299]
Hey @rwaltr -- I saw your tagline and thought maybe we could collaborate. I'm nearing the completion of a cross-platform Chezmoi project and thought you might want to check it out. I might be slightly more more mad than you lol:

I thought you might want to join this Chezmoi gitter community I'm starting https://gitter.im/megabyte-labs/community# -- trying to invite a handful of Chezmoi developers with 1k+ commits.

**Comment by rwaltr** [comment]
Howdy @ProfessorManhattan,

I am not interested in creating a glitter account. However, I did check out your sexy-start repo. Which I assume is the project you are mentioning, quite ambitious.

You have some nifty ideas that I plan to bring back into my dotfiles. If I see anything that stands out, I'll throw a PR your way.

Thank you!

**Comment by ProfessorManhattan** [comment]
> Howdy @ProfessorManhattan,
> 
> I am not interested in creating a gitter account. However, I did check out your sexy-start repo. Which I assume is the project you are mentioning, quite ambitious.
> 
> You have some nifty ideas that I plan to bring back into my dotfiles. If I see anything that stands out, I'll throw a PR your way.
> 
> Thank you!

Hey the repo is actually https://GitHub.com/megabyte-labs/install.doctor - any feedback would be appreciated thanksssss
